# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a06775e467f8b76c2a51b0814cd255d2d7d57dd8771bf75564eeed44452d1390e2335a54d7c0e7ffdcc7a5407dbfb7c3fd6174c281a794aeb91c4b1f22faa36a

test:
  secret_key_base: f17a1619552ede9b6665ec5a86c1ac81a8dc6b347b1129237e3de01914388cef2bd5e074722e4f92f793b927baab4f6050067cae44389fb11304c9631f357ee3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
